services:
  - type: web
    name: acta-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run prisma:generate && npm run prisma:deploy
    startCommand: npm start
    autoDeploy: true
